name: Check Markdown

on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          check-modified-files-only: 'no'
          base-branch: 'main'
      - name: markdownlint-cli2-action
        uses: DavidAnson/markdownlint-cli2-action
